<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Model_tests.TestModel-20220204162226" tests="4" file="Model_tests.py" time="0.017" timestamp="2022-02-04T16:22:26" failures="0" errors="4" skipped="0">
	<testcase classname="Model_tests.TestModel" name="test_filter_articles_by_title" time="0.008" timestamp="2022-02-04T16:22:26">
		<error type="ModuleNotFoundError" message="No module named 'src'"><![CDATA[Traceback (most recent call last):
  File "/Library/anaconda3/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/anaconda3/lib/python3.9/unittest/case.py", line 592, in run
    self._callTestMethod(testMethod)
  File "/Library/anaconda3/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/Users/manuelfreistein/Desktop/Dev/FST_Excercise/src/Conception/Model_tests.py", line 23, in test_filter_articles_by_title
    from Model import Model
  File "/Users/manuelfreistein/Desktop/Dev/FST_Excercise/src/Conception/Model.py", line 12, in <module>
    from src.Databases import Article_Info_Conception as aic_db
ModuleNotFoundError: No module named 'src'
]]></error>
	</testcase>
	<testcase classname="Model_tests.TestModel" name="test_filter_contributors_by_last_name" time="0.003" timestamp="2022-02-04T16:22:26">
		<error type="ModuleNotFoundError" message="No module named 'src'"><![CDATA[Traceback (most recent call last):
  File "/Library/anaconda3/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/anaconda3/lib/python3.9/unittest/case.py", line 592, in run
    self._callTestMethod(testMethod)
  File "/Library/anaconda3/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/Users/manuelfreistein/Desktop/Dev/FST_Excercise/src/Conception/Model_tests.py", line 29, in test_filter_contributors_by_last_name
    from Model import Model
  File "/Users/manuelfreistein/Desktop/Dev/FST_Excercise/src/Conception/Model.py", line 12, in <module>
    from src.Databases import Article_Info_Conception as aic_db
ModuleNotFoundError: No module named 'src'
]]></error>
	</testcase>
	<testcase classname="Model_tests.TestModel" name="test_get_all_article_suggestions" time="0.003" timestamp="2022-02-04T16:22:26">
		<error type="ModuleNotFoundError" message="No module named 'src'"><![CDATA[Traceback (most recent call last):
  File "/Library/anaconda3/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/anaconda3/lib/python3.9/unittest/case.py", line 592, in run
    self._callTestMethod(testMethod)
  File "/Library/anaconda3/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/Users/manuelfreistein/Desktop/Dev/FST_Excercise/src/Conception/Model_tests.py", line 5, in test_get_all_article_suggestions
    from Model import Model
  File "/Users/manuelfreistein/Desktop/Dev/FST_Excercise/src/Conception/Model.py", line 12, in <module>
    from src.Databases import Article_Info_Conception as aic_db
ModuleNotFoundError: No module named 'src'
]]></error>
	</testcase>
	<testcase classname="Model_tests.TestModel" name="test_get_article_suggestion_by_id" time="0.003" timestamp="2022-02-04T16:22:26">
		<error type="ModuleNotFoundError" message="No module named 'src'"><![CDATA[Traceback (most recent call last):
  File "/Library/anaconda3/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/anaconda3/lib/python3.9/unittest/case.py", line 592, in run
    self._callTestMethod(testMethod)
  File "/Library/anaconda3/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/Users/manuelfreistein/Desktop/Dev/FST_Excercise/src/Conception/Model_tests.py", line 17, in test_get_article_suggestion_by_id
    from Model import Model
  File "/Users/manuelfreistein/Desktop/Dev/FST_Excercise/src/Conception/Model.py", line 12, in <module>
    from src.Databases import Article_Info_Conception as aic_db
ModuleNotFoundError: No module named 'src'
]]></error>
	</testcase>
</testsuite>
